# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "I0C5wuXl8Re3mSJJpyElExibT1u+ScRNCjxs+0MeEMoVx7GIad2qdc9Go1Jh8VkCUvpcCa7E8Qss2NTk3jWLaE5QW0HtWqDlmMA036gfVqkqetS4TsVxssDF404LheiV4QklOWZY13kMV0dapChCjzJqWfuOK2+EbVjLeVzDa/o7BkwS+m3ehBRPMcprnIaLUPaL2lzJslxVO+5SJyg6O+ZeHJklfiz2Te7e9tquCusBFOD2Wa3JiNLPPy/dQMtQK118/O2R12cXpfzx0agi6CWGeB0wU90KKYlwumK/NiXFz0adwzlSr0XOHEC3ZdWkyzzxxNlkKiQoe+y0/EA8LMv/tCN6pyAiJHR+0MdzBLBQaabJo+lDqVxbxmdFEEMBfTgCAnhWjuCqS3eIBE8dN9bTmkDJnSXEBB6UcS0jgs2Al19SS8N2fCbsTR5WaFxiBIGJv/DrW+imutTocCYfCBBGALfUF41ZmImTVFP7Y3gQEXjuEt6s2K9EhAR52pAcaOYFeDi9tKalwC4SFUgqIqNXG+cFp6JKY7PV3e99iPiC/iO7vqKiUI21AC/O1ZXetPzaURJBjMykiKWhZE3AVmyh5bIsVFNvL2d/h0JgqChIOWHKvRb/1DTN6I5dJLPtvQMdV8V0hjHBz47zx8ZW5JcBuLp9PCX7//nvIdkoM2o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
